("ACI HealthCare Limited"),
("Active Fine Chemicals Ltd."),
("Ad-din Pharmaceuticals Ltd."),
("Adova Pharmaceuticals Ltd."),
("Advanced Chemical Industries Limited"),
("Advent Pharma Ltd."),
("AFC Agro Biotech Ltd."),
("Al-Madina Pharmaceuticals Ltd."),
("Albion Specialized Pharma Limited"),
("Alco Pharma Limited"),
("Alkad Laboratories"),
("Allied Pharmaceuticals Ltd."),
("Ambee Pharmaceuticals Ltd."),
("Amico Laboratories Ltd."),
("Amulet Pharmaceuticals Ltd."),
("APC Pharma Limited"),
("Apex Pharma Ltd."),
("Apollo Pharmaceutical Laboratories Ltd."),
("Arges Life Science Ltd."),
("Aristopharma Limited"),
("Army Pharma Limited"),
("Asiatic Laboratories Ltd."),
("Astra Biopharmaceuticals Ltd."),
("Avarox Pharmaceuticals Ltd."),
("Aztec Pharmaceuticals Ltd."),
("Bangladesh Antibiotic Industries Limited"),
("Beacon Pharmaceuticals PLC"),
("Belsen Pharmaceuticals Ltd."),
("Bengal Drugs & Chemical Works Pharm. Ltd."),
("Bengal Remedies Ltd."),
("Benham Pharmaceuticals Ltd."),
("Beximco Pharmaceuticals Ltd."),
("Bexter Pharmaceuticals"),
("Biogen Pharmaceuticals Ltd."),
("Biopharma Ltd."),
("Bridge Pharmaceuticals Ltd."),
("Bristol Pharma Ltd."),
("C2C Pharma Limited"),
("Centeon Pharma Limited"),
("Central Pharmaceutical Ltd."),
("Chemist Laboratories Ltd."),
("Cipla Ltd."),
("Concord Pharmaceuticals Ltd."),
("Cosmic Pharma Ltd."),
("Cosmo Pharma Laboratories Ltd."),
("DBL Pharmaceuticals Limited"),
("Decent Pharma Laboratories Ltd."),
("Delta Pharma Limited"),
("Desh Pharmaceuticals Ltd."),
("Dider Pharma Ltd.,"),
("Doctor Tims Pharmaceuticals Ltd."),
("Doctor's Chemicals Works Ltd."),
("Drug International Ltd."),
("EDCL (Dhaka)"),
("Edruc Ltd."),
("EMCS Pharma Limited"),
("Eon Pharmaceuticals Ltd."),
("Ereba Capsule Limited"),
("Eskayef Pharmaceuticals Ltd."),
("Ethical Drug Ltd."),
("Euro Pharma Ltd."),
("Everest Pharmaceuticals Ltd."),
("FnF Pharmaceuticals Ltd."),
("G. A. Company Ltd."),
("General Pharmaceuticals Ltd."),
("Gentry Pharmaceuticals Ltd."),
("Genvio Pharma Ltd."),
("Get Well Limited"),
("Globe Pharmaceuticals Ltd."),
("Globex Pharmaceuticals Ltd."),
("Gonoshasthaya Pharmaceuticals Ltd."),
("Goodman Pharmaceuticals Ltd"),
("Greenland Pharmaceuticals Ltd."),
("Guardian Healthcare Ltd."),
("Healthcare Pharmaceuticals Ltd."),
("Hudson Pharmaceuticals Ltd."),
("Ibn Sina Pharmaceutical Ind. Ltd."),
("Incepta Pharmaceuticals Ltd."),
("Indo-Bangla Pharmaceuticals Ltd."),
("Islam Oxygen (Pvt) Ltd."),
("Jayson Pharmaceuticals Ltd."),
("Jenphar Bangladesh Ltd."),
("JMI Industrial Gas Ltd."),
("JP Pharmaceuticals (Veterinary)"),
("JR Pharmaceuticals Ltd."),
("Kemiko Pharmaceuticals Ltd."),
("Kumudini Pharma Ltd."),
("Labaid Pharmaceuticals Ltd."),
("Leader Pharmaceuticals Limited"),
("Leon Pharmaceuticals Ltd."),
("Libra Infusion Limited"),
("Linde Bangladesh Limited"),
("Maks Drugs Ltd."),
("Marksman Pharmaceutical Ltd."),
("Medicon Pharmaceuticals Ltd."),
("Medimet Pharmaceuticals Ltd."),
("MedRx Life Science Ltd."),
("Millat Pharmaceuticals Ltd."),
("Modern Pharmaceuticals Ltd."),
("Momtaz Pharmaceuticals Ltd."),
("Monicopharma Limited"),
("MSF Pharmaceuticals Ltd.,"),
("MST Pharma and Healthcare Ltd."),
("Mundipharma (Bangladesh) Pvt. Ltd."),
("Mystic Pharmaceuticals Ltd."),
("Naafco Pharma Ltd."),
("National Drug Company Ltd."),
("Navana Pharmaceuticals Ltd."),
("Newtec Pharmaceuticals Ltd."),
("Nipa Pharmaceuticals Ltd."),
("NIPRO JMI Pharma Limited"),
("Novartis (Bangladesh) Ltd."),
("Novatek Pharmaceuticals Ltd."),
("Novo Healthcare and Pharma Ltd."),
("Novus Pharmaceuticals Ltd."),
("Nuvista Pharma Ltd"),
("One Pharma Ltd."),
("Opsonin Bulk Drugs Ltd."),
("Opsonin Pharma Limited"),
("Orion Infusion Ltd."),
("Orion Pharma Ltd."),
("OSL Pharma Ltd."),
("Oyster Pharmaceuticals Ltd."),
("Pacific Pharmaceuticals Ltd."),
("Peertop Pharmaceuticals Ltd.,"),
("Peoples Pharma Ltd."),
("Pharmacil Ltd."),
("Pharmasia Ltd."),
("Pharmatek Chemicals Ltd."),
("Pharmik Laboratories Ltd."),
("Physic Pharmaceuticals Ltd.,"),
("Popular Pharmaceuticals PLC"),
("Premier Pharmaceuticals Ltd."),
("Prime Pharmaceuticals Ltd."),
("Pristine Chem Limited"),
("Pristine Pharmaceuticals"),
("Promixco Pharmaceutical Ltd."),
("Purbadesh Chemists Ltd.,"),
("Quality Pharmaceuticals (Pvt) Ltd."),
("Radiant Pharmaceuticals Ltd."),
("Rahman Chemicals Ltd."),
("Rampart-Power Bangladesh Ltd."),
("Rangs Pharmaceuticals Ltd."),
("Reckitt Benckiser Bangladesh Ltd."),
("Reliance Pharmaceuticals Ltd."),
("Reman Drug Laboratories Ltd."),
("Remo Chemical Ltd."),
("Renata Limited"),
("Rephco Pharmaceuticals Ltd."),
("RN Pharmaceuticals"),
("Royal Pharmaceuticals Ltd."),
("S. N. Pharmaceuticals Ltd."),
("Save Pharmaceuticals Ltd."),
("Seba Laboratories Ltd."),
("Sharif Pharmaceuticals Ltd."),
("Shinil Pharma Limited"),
("Silco Pharmaceuticlas Ltd."),
("Silva Pharmaceuticals Ltd."),
("SMC Enterprise Limited"),
("Sodical Chemical Ltd."),
("Somatec Pharmaceuticals Ltd."),
("Sonargaon Steel Fabricate Ltd., (Oxygen Plant)"),
("Spectra International Ltd.,"),
("Spectra Oxygen Limited"),
("Square Pharmaceuticals PLC."),
("Standard Laboratories Ltd."),
("Sun Pharmaceutical (Bangladesh) Ltd."),
("Sunman-Birdem Pharma Ltd."),
("Super Power Pharmaceuticals Ltd."),
("Supreme Pharmaceuticals Ltd."),
("Synovia Pharma PLC."),
("Team Pharmaceuticals Ltd."),
("Techno Drugs Ltd."),
("The ACME Laboratories Ltd."),
("The White Horse Pharmaceuticals Ltd."),
("UNIDO Pharmaceuticals Ltd."),
("Unimed Unihealth Pharmaceuticals Ltd."),
("Union Oxygen Limited"),
("Union Pharmaceuticals Ltd."),
("Unique Pharmaceutical Ltd."),
("United Chemicals & Pharmaceuticals Ltd."),
("Veritas Pharmaceuticals Ltd."),
("Vion Pharmaceuticals (Veterinary)"),
("Virgo Pharmaceuticals Ltd."),
("Vision Drugs Limited (Veterinary)"),
("World API Chemical Industry Ltd."),
("Zenith Pharmaceuticals Ltd."),
("Zhaofeng Gelating Limited"),
("Ziska Pharmaceuticals Ltd."),
